version: "3.8"
services:

    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - database

    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - database

    database:
        container_name: database
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - database:/var/lib/mysql



volumes:
    database:
    composer:
